name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # يسمح بالتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv virtualenv libncurses5
          pip3 install buildozer cython

      - name: Build APK with Buildozer
        run: |
          # إصلاح مشاكل التوافق في البيئة السحابية
          buildozer android debug deploy run
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: bin/*.apk
